version: '3.1'

services:
  db:
    image: postgres:11
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leaguedex
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - pern-app
  api:
    image: leaguedex-api
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
      - ./server/prisma/.env
    depends_on:
      db:
        condition: 'service_healthy'
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - pern-app
  client:
    image: leaguedex-client:production
    ports:
      - 8080:80
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge
