name: CI/CD

on:
  push:
    branches: [feature/dockerize-app]

# Trigger on master for staging
# Trigger on release for production
# Determine docker image tag
  # staging -> commit sha
  # production -> release tag
# build images
# push images (dockerhub)
# deploy to correct droplet

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker Images
      run: |
        pwd
        ls
        make build-production-client