name: CI/CD

on:
  push:
    branches: [feature/dockerize-app]

# Trigger on master for staging
# Trigger on release for production
# Determine docker image tag
  # staging -> commit sha
  # production -> release tag
# build images
# push images (dockerhub)
# deploy to correct droplet

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set ENV
      run: |-
        echo ${GITHUB_REF##*/}
        echo ${GITHUB_SHA}

        if [ ${GITHUB_REF##*/} = "dockerize-app" ]; then
          echo "ENV=staging" >> $GITHUB_ENV
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        else 
          echo "ENV=prod" >> $GITHUB_ENV
          echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
        fi
        echo $ENV
        echo $DOCKER_TAG

    # - name: Build Docker Images
    #   run: make build-images

    # - name: Push Docker Images
    #   run: make push-images