name: STAGING

on:
  push:
    branches: [development]

jobs:
  build_client:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --force
      - run: yarn run build
      - run: rm -r /var/www/html/staging-leaguedex/*
      - run: mv ./build/* /var/www/html/staging-leaguedex
  build_server:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm -r ../../staging_leaguedex/*
      - run: mv ./* ../../staging_leaguedex
      - run: cp ../../server.env ../../staging_leaguedex/.env
      - run: cp ../../prisma.env ../../staging_leaguedex/prisma/.env
      - run: cp ../../.prettierrc ../../staging_leaguedex/
      - run: cp ../../.prettierignore ../../staging_leaguedex/
      - run: cd ../../staging_leaguedex && yarn install --force
      - run: cd ../../staging_leaguedex && yarn run:prettier
      - run: cd ../../staging_leaguedex && yarn migrate:staging
      - run: cd ../../staging_leaguedex && yarn restart:staging
